export enum StatusCode {
  OK = 200,
  CREATED = 201,
  ACCEPTED = 202,
  NO_CONTENT = 204,
  MOVED_PERMANENTLY = 301,
  FOUND = 302,
  NOT_MODIFIED = 304,
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  METHOD_NOT_ALLOWED = 405,
  CONFLICT = 409,
  INTERNAL_SERVER_ERROR = 500,
  NOT_IMPLEMENTED = 501,
  BAD_GATEWAY = 502,
  SERVICE_UNAVAILABLE = 503,
  GATEWAY_TIMEOUT = 504,
}

export const ReasonStatusCode: { [key in StatusCode]: string } = {
  [StatusCode.OK]: 'OK',
  [StatusCode.CREATED]: 'Created',
  [StatusCode.ACCEPTED]: 'Accepted',
  [StatusCode.NO_CONTENT]: 'No Content',
  [StatusCode.MOVED_PERMANENTLY]: 'Moved Permanently',
  [StatusCode.FOUND]: 'Found',
  [StatusCode.NOT_MODIFIED]: 'Not Modified',
  [StatusCode.BAD_REQUEST]: 'Bad Request',
  [StatusCode.UNAUTHORIZED]: 'Unauthorized',
  [StatusCode.FORBIDDEN]: 'Forbidden',
  [StatusCode.NOT_FOUND]: 'Not Found',
  [StatusCode.METHOD_NOT_ALLOWED]: 'Method Not Allowed',
  [StatusCode.CONFLICT]: 'Conflict',
  [StatusCode.INTERNAL_SERVER_ERROR]: 'Internal Server Error',
  [StatusCode.NOT_IMPLEMENTED]: 'Not Implemented',
  [StatusCode.BAD_GATEWAY]: 'Bad Gateway',
  [StatusCode.SERVICE_UNAVAILABLE]: 'Service Unavailable',
  [StatusCode.GATEWAY_TIMEOUT]: 'Gateway Timeout',
}
